name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€

on: [push, workflow_dispatch]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ Triggered by ${{ github.event_name }} event."
      - run: echo "ğŸ§ Running on ${{ runner.os }}!"
      - run: echo "ğŸ” Branch: ${{ github.ref }} | Repo: ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "ğŸ’¡ Repo cloned."
      - run: echo "ğŸ–¥ï¸ Ready to test code."
      - name: List files
        run: |
          ls ${{ github.workspace }}
      - run: echo "ğŸ Job status is ${{ job.status }}."

